[project]
name = "todo"
version = "0.1.0"
description = "Tool to handle 'to do' app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rich",
]

[project.scripts]
todo = "main:main"
